rules:
  color-hex-case: lower
  color-hex-length: short
  color-named: never
  color-no-invalid-hex: true

  font-family-name-quotes: always-unless-keyword
  font-family-no-duplicate-names: true
  font-weight-notation: numeric

  function-calc-no-unspaced-operator: true
  function-comma-newline-after: never-multi-line
  function-comma-newline-before: always-multi-line
  function-comma-space-after: always
  function-comma-space-before: always-single-line
  function-linear-gradient-no-nonstandard-direction: true
  function-max-empty-lines: 0
  function-name-case: lower
  function-parentheses-newline-inside: always-multi-line
  function-parentheses-space-inside: never
  function-url-data-uris: never
  function-url-no-scheme-relative: true
  function-url-quotes: always
  function-whitespace-after: always
  function-blacklist:
    - rgb
    - rgba
    - hwb
    - hsl
    - gray

  number-leading-zero: always
  number-max-precision: 2
  number-no-trailing-zeros: true
  string-no-newline: true
  string-quotes: double
  length-zero-no-unit: true
  time-no-imperceptible: true
  unit-case: lower
  unit-no-unknown: true
  value-keyword-case: lower
  value-no-vendor-prefix: true

  custom-property-no-outside-root: true
  shorthand-property-no-redundant-values: true

  property-case: lower
  property-no-vendor-prefix: true
  keyframe-declaration-no-important: true

  declaration-bang-space-after: never
  declaration-bang-space-before: always
  declaration-colon-space-after: always
  declaration-colon-space-before: never

  declaration-block-no-shorthand-property-overrides: true
  declaration-block-no-ignored-properties: true

  declaration-block-no-duplicate-properties:
    - true
    - ignore:
      - consecutive-duplicates-with-different-values

  block-opening-brace-newline-after: always
  block-opening-brace-newline-before: always

  value-list-comma-newline-after: never-multi-line
  value-list-comma-newline-before: always-multi-line
  value-list-comma-space-after: always
  value-list-comma-space-before: always-single-line
  value-list-max-empty-lines: 0

  at-rule-empty-line-before: always
  at-rule-name-case: lower
  at-rule-no-vendor-prefix: true
  at-rule-blacklist:
    - charset
    - namespace
    - document
    - viewport

  comment-no-empty: true
  comment-whitespace-inside: always

  indentation: 4
  max-empty-lines: 1
  max-line-length: 80
  max-nesting-depth: 3
  no-browser-hacks: true
  no-duplicate-selectors: true
  no-empty-source: true
  no-eol-whitespace: true
  no-extra-semicolons: true
  no-invalid-double-slash-comments: true
  no-missing-end-of-source-newline: true
  no-unknown-animations: true
